### ISSUE TITLE
ME Wireless Transceiver Freezes/Crashes the Game

### ISSUE THREAD

**Issue by DarkDragonRises1** [the9grounds/AE-Additions#109]
Hey, Im currently playing ATM 8 with some friends.
The game just crashes/freezes when i want to look into the ME Wireless Transceiver. 
I cant get into the screen where i can set my broadcast / subscriber settings.
I hope you can fix that :)

**Comment by Beachman4** [comment]
Do you happen to have a crash log?

**Comment by DarkDragonRises1** [comment]
The client crash Message is: Internal Exception java.lang.NullpointerException

Crash Log: Nov 13, 2022 6:35:46 PM com.google.common.cache.LocalCache processPendingNotifications
WARNING: Exception thrown by removal listener
java.lang.ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class journeymap.client.waypoint.WaypointGroup (com.google.gson.internal.LinkedTreeMap is in module com.google.gson@2.8.9 of loader 'MC-BOOTSTRAP' @1c1bbc4e; journeymap.client.waypoint.WaypointGroup is in module journeymap@5.9.0beta2 of loader 'TRANSFORMER' @1179fc8c)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.WaypointGroupStore.get(WaypointGroupStore.java:47)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.Waypoint.getGroup(Waypoint.java:525)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.WaypointStore.lambda$getAll$0(WaypointStore.java:74)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.Iterators$5.computeNext(Iterators.java:670)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.WaypointGroupStore$2.onRemoval(WaypointGroupStore.java:240)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1814)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3467)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3443)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache$Segment.put(LocalCache.java:2844)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache.put(LocalCache.java:4196)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.cache.LocalCache$LocalManualCache.put(LocalCache.java:4880)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.WaypointGroupStore.load(WaypointGroupStore.java:130)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.WaypointGroupStore.ensureLoaded(WaypointGroupStore.java:91)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.WaypointGroupStore.get(WaypointGroupStore.java:46)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.waypoint.Waypoint.<init>(Waypoint.java:242)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.api.impl.PluginWrapper.show(PluginWrapper.java:132)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.api.impl.ClientAPI.show(ClientAPI.java:165)
	at TRANSFORMER/waystones@11.1.0/net.blay09.mods.waystones.compat.JourneyMapAddon.updateWaypoint(JourneyMapAddon.java:125)
	at TRANSFORMER/waystones@11.1.0/net.blay09.mods.waystones.compat.JourneyMapAddon.updateAllWaypoints(JourneyMapAddon.java:95)
	at TRANSFORMER/waystones@11.1.0/net.blay09.mods.waystones.compat.JourneyMapAddon.lambda$onKnownWaystones$0(JourneyMapAddon.java:73)
	at TRANSFORMER/waystones@11.1.0/net.blay09.mods.waystones.compat.JourneyMapAddon.onEvent(JourneyMapAddon.java:65)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.api.impl.PluginWrapper.notify(PluginWrapper.java:373)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.api.impl.ClientEventManager.fireMappingEvent(ClientEventManager.java:81)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.JourneymapClient.startMapping(JourneymapClient.java:557)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:100)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:83)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:661)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.event.handlers.StateTickHandler.onClientTick(StateTickHandler.java:56)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.event.forge.ForgeClientTickEvent.onClientTick(ForgeClientTickEvent.java:23)
	at TRANSFORMER/journeymap@5.9.0beta2/journeymap.client.event.forge.__ForgeClientTickEvent_onClientTick_ClientTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.1.47/net.minecraftforge.event.ForgeEventFactory.onPreClientTick(ForgeEventFactory.java:814)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1718)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.47/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

  <log4j:Event logger="com.connectivity.Connectivity" timestamp="1668360966081" level="WARN" thread="Netty Client IO #1">
    <log4j:Message><![CDATA[java.lang.NullPointerException]]></log4j:Message>
  </log4j:Event>
18:36:06.082
XML_ERROR_PARSING

**Comment by DarkDragonRises1** [comment]
18:36:06.083
Packet not registered: ClientboundDisconnectPacket
18:36:06.083
io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet


I forgot that :)

**Comment by DarkDragonRises1** [comment]
Im not sure if the Error Message above the right one i cleared the output and tried again:

18:43:13.754
Can't get entityTexture for translation{key='entity.naturalist.firefly', args=[]} (SUPPRESSED)
18:43:13.754
java.lang.Throwable: Can't get entityTexture for translation{key='entity.naturalist.firefly', args=[]}
18:43:20.526
**java.lang.NullPointerException**
18:43:20.527
Packet not registered: ClientboundDisconnectPacket
18:43:20.527
io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
18:43:20.899
Unloading synced configs from server
18:43:20.899
Released client Flux Networks cache
18:43:20.899
JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
18:43:20.899
JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
18:43:20.899
Stopping JEI
18:43:20.902
Removed all colony views
18:43:20.904
Mapping halted in C:\Users\chris\curseforge\minecraft\Instances\All the Mods 8 - ATM8 - 1.19.2\journeymap\data\mp\Minecraft~Server_2c1c1297~2be3~4935~9c7e~9e304647f19c\minecraft:overworld
18:43:29.174
Stopping worker threads
18:43:29.175
Client logged off. Resetting Pack Meta and Reloading State

**Comment by DarkDragonRises1** [comment]
This should be the cause:

`18:53:20.684
java.lang.NullPointerException
18:53:20.684
Packet not registered: ClientboundDisconnectPacket
18:53:20.684
io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet`

**Comment by Wailrone** [comment]
Any news with this issue ? It seems that we need to restart the server to fix this issue temporarily. When you add any channel, the block is broken and the client crash. So you need to restart your server, create your channel, restart again, and you can use the block. But sometimes, the transceiver doesn't work so you need to restart your server again.

**Comment by Mihoshika** [comment]
Got the same issue. 
`[00:46:33] [Netty Client IO #9/WARN] [co.co.Connectivity/]: java.lang.NullPointerException
[00:46:33] [Netty Client IO #9/WARN] [co.co.Connectivity/]: Packet not registered: ClientboundDisconnectPacket
[00:46:33] [Netty Client IO #9/WARN] [co.co.Connectivity/]: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
[00:46:34] [Render thread/INFO] [configured/]: Unloading synced configs from server
[00:46:34] [Render thread/INFO] [FluxNetworks/]: Released client Flux Networks cache
[00:46:34] [Render thread/INFO] [me.je.fo.st.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[00:46:34] [Render thread/INFO] [me.je.fo.st.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[00:46:34] [Render thread/INFO] [me.je.li.st.JeiStarter/]: Stopping JEI`

**Comment by Beachman4** [comment]
Sorry for the delay folks. I'll be looking into this today.

Would anyone be able to provide me with a set of steps to take on a fresh world so that I can reproduce and find the issue?

**Comment by Beachman4** [comment]
I resolved an issue about stale subscribers still being on the channel and thus causing issues for the newer subscribers.

Can you try this jar out and tell me if it's any different? https://github.com/the9grounds/AE-Additions/suites/10657018809/artifacts/532661955

**Comment by Shobs** [comment]
Using your mod as part of the ATM8 modpack and it seems that your fix worked on my end.  I am no longer crashing when interacting with transceiver.

**Comment by Beachman4** [comment]
I've released this fix on 1.19.2 and 1.18.2. Please let me know if you have any further issues with this.
