### ISSUE TITLE
game crash on 1.12.2

### ISSUE THREAD

**Issue by zeng-github01** [the9grounds/AE-Additions#135]
`Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.the9grounds.aeadditions.crafting.CraftingPattern.getCondensedInputs(CraftingPattern.java:76)
	at com.the9grounds.aeadditions.tileentity.TileEntityFluidCrafter.updateWatcher(TileEntityFluidCrafter.kt:359)
	at com.the9grounds.aeadditions.tileentity.TileEntityFluidCrafter.updateWatcher(TileEntityFluidCrafter.kt:373)
	at appeng.me.cache.CraftingGridCache.addNode(CraftingGridCache.java:166)
	at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:50)
	at appeng.me.Grid.add(Grid.java:166)
	at appeng.me.GridNode.setGrid(GridNode.java:212)
	at appeng.me.GridPropagator.visitNode(GridPropagator.java:37)
	at appeng.me.GridNode.visitorNode(GridNode.java:471)
	at appeng.me.GridNode.beginVisit(GridNode.java:162)
	at appeng.me.GridConnection.create(GridConnection.java:239)
	at appeng.me.GridNode.findConnections(GridNode.java:405)
	at appeng.me.GridNode.updateState(GridNode.java:180)
	at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:128)
	at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:121)
	at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:255)
	at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:500)
	at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:196)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:175)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1375_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by zeng-github01** [comment]
A possible patch. Tested, doesn't seem to crash
https://github.com/zeng-github01/AE-Additions/commit/7052e5a045e9cfdebbb57cde8219535a288b48b6
