### ISSUE TITLE
Mod conflict with Planar Artifice: Continuation

### ISSUE THREAD

**Issue by Rumcajz23th** [the9grounds/AE-Additions#151]
Hello i have problem that this mod have the same name ( or ID) like mod called Aether Additions.
problem is, that the Planar Artifice has build in integration with mod Aether Additions and when this mod detect mod with name aeaditions it is thinking that it is Aether one and is trying to comunicate with the mod. And because this mod is not Aether aditions, Minecraft crash on startup...

I tested it few times on separate mod pack only with essential mods and crash will hapend everytime when i try use you'r  and Planar Artifice mods together.

Is here a way to rename or set different ID in this mod? Planar Artifice is a year without update, so i think there will be no support for it, but because this mod is new, i hope that fix is possible from this site.

Thank you for any advice or help.

Here is crash log:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Planar Artifice Coremod (planarartifice-1.4.0-pre7.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/10/24 10:22 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.NoClassDefFoundError: com/virtualesence/aetheradditions/init/ModItems
	at leppa.planarartifice.compat.aether.AetherAdditionsHandler.registerAspects(AetherAdditionsHandler.java:15)
	at leppa.planarartifice.compat.PACompatHandler$$Lambda$457/1506634888.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at leppa.planarartifice.compat.PACompatHandler.registerAspects(PACompatHandler.java:97)
	at leppa.planarartifice.registry.Registrar.registerAspects(Registrar.java:87)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_Registrar_registerAspects_AspectRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:45)
	at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:82)
	at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:54)
	at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.virtualesence.aetheradditions.init.ModItems
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1147217776 bytes (1094 MB) / 1776812032 bytes (1694 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                               | Signature                                |
	|:----- |:------------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| LCHIJ | minecraft           | 1.12.2       | minecraft.jar                        | None                                     |
	| LCHIJ | mcp                 | 9.42         | minecraft.jar                        | None                                     |
	| LCHIJ | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge               | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | appliedenergistics2 | rv6-stable-7 | appliedenergistics2-rv6-stable-7.jar | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJ | forgelin            | 1.8.4        | Forgelin-1.8.4.jar                   | None                                     |
	| LCHIJ | aeadditions         | 1.3.8        | AEAdditions-1.12.2-1.3.8.jar         | None                                     |
	| LCHIJ | baubles             | 1.5.2        | Baubles-1.12-1.5.2.jar               | None                                     |
	| LCHIE | thaumcraft          | 6.1.BETA26   | Thaumcraft-1.12.2-6.1.BETA26.jar     | None                                     |
	| LCHI  | planarartifice      | 1.4.0-pre7   | planarartifice-1.4.0-pre7.jar        | None                                     |

	Loaded coremods (and transformers): 
Planar Artifice Coremod (planarartifice-1.4.0-pre7.jar)
  leppa.planarartifice.core.PATransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.76' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
```

**Comment by Rumcajz23th** [comment]
sorry for spam, i see, that this problem was reported here #129
